#!/usr/bin/bash
$2/$4-$5/configure \
    --host=$3 \
    --disable-pciaccess \
    --disable-ipv6 \
    --disable-libdrm \
    --disable-glx \
    --disable-int10-module \
    --disable-vgahw \
    --disable-glamor \
    --disable-dri3 \
    --disable-dri2 \
    --disable-dri \
    --disable-xephyr \
    --disable-xnest \
    --disable-xwayland \
    --disable-config-udev \
    --disable-systemd-logind \
    --prefix=$1 \
    --without-systemd-daemon \
    --disable-selective-werror \
    --disable-strict-compilation \
    --with-sysroot=$6 \
    --disable-static --enable-shared \
    --with-xkb-path=/usr/share/X11/xkb \
    --with-xkb-bin-directory=/usr/bin \
    --localstatedir=/var \
    --sharedstatedir=/com \
    --sysconfdir=/etc \
    --runstatedir=/var/run \
    ac_cv_func_epoll_create1=no
